# Jykell configuration
#markdown: redcarpet
#highlighter: pygments
markdown: kramdown
highlighter: rouge
paginate: 5
language: 'en-uk'

# Website info
name: "Karki's Blog"
description: "It's *my* blog!"

# Author's info
author: 'Deepak Karki'
# edit 'categories' in the front matter of every post to match this username
nickname: 'karki'
bio: 'I am a developer'
location: 'Bangalore, India'
url: 'http://deepakkarki.github.io/blog/'
image: 'assets/images/casper.png'

short_url: 'deepakkarki.github.io/blog/'
# google_analytics: UA-69281367-1
# disqus: username
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
# This is the {{ site.baseurl }}
baseurl: '/blog/'

# Permalinks
permalink: /:year/:title
# permalink: /author/:username
# permalink: /tag/:tag


# gems and other configs
gems: [jekyll-paginate]
exclude: [vendor]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...
