# Jykell configuration
#markdown: redcarpet
#highlighter: pygments
markdown: kramdown
highlighter: rouge
paginate: 5
language: 'en-uk'

# Website info
name: "Deepak Karki | Blog"
description: "A blog on tech, education, and philosophy. Mostly opinionated."

# Website defaults
defaults: # This is a keyword - http://jekyllrb.com/docs/configuration/#front-matter-defaults
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      logo: 'assets/images/logo-white.png' # accessible as page.logo
      cover: 'assets/images/cover1.jpg'    # page.cover
# -
#   scope:
#     path: "projects" # Any html files that exist in the projects/ folder
#   values:
#     key1: 'value1'
#     key2: 'value2'


# Author's info
author: 'Deepak Karki'
# edit 'categories' in the front matter of every post to match this username
nickname: 'karki'
bio: 'Developer | Maker | Hacker'
location: 'Bangalore, India'
url: 'http://deepakkarki.github.io/blog/'
image: 'assets/images/profile.jpg'

short_url: 'deepakkarki.github.io/blog/'
# google_analytics: UA-69281367-1
# disqus: username
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
# This is the {{ site.baseurl }}
baseurl: '/blog/'

# Permalinks
permalink: /:year/:title
# permalink: /author/:username
# permalink: /tag/:tag


# gems and other configs
gems: [jekyll-paginate]
exclude: [vendor]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...
